# Utilizar a imagem alpine como base para um container leve
FROM alpine:latest

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Instalar dependências necessárias
RUN apk add --no-cache wget

# Baixar o binário do PocketBase (ajuste a versão conforme necessário)
RUN wget https://github.com/pocketbase/pocketbase/releases/download/v0.12.0/pocketbase_0.12.0_linux_amd64.zip \
    && unzip pocketbase_0.12.0_linux_amd64.zip \
    && rm pocketbase_0.12.0_linux_amd64.zip

# Expor a porta padrão do PocketBase
EXPOSE 8090

# Comando para iniciar o PocketBase
CMD ["./pocketbase.exe", "serve", "--http", "0.0.0.0:8090"]