services:
  frontend:
    build: ./frontend
    image: src/frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    ports:
      - "8000:8000"
    depends_on:
      - backend
    container_name: fillmore-frontend  
  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8001:8000"
    container_name: fillmore-backend